### PR TITLE
Safer dispatch queue deinitialization

### LINKED ISSUE #604: Process keep running after closing the game window
I noted some unusual memory consumption on my computer. After investigating, I found that the _OpenSpades_ process is keeping running after I close the main game window.

**If I only start the launcher** (using the `SPACE` key), **closing it effectively ends the main process.**

Process execution
------------------

I used the command `ps -C openspades -m -o state,ppid,pid,thcount,tid,%cpu,%mem,etime,command` to show information about the processes.

After starting the game:

    S  PPID   PID THCNT   TID %CPU %MEM     ELAPSED COMMAND
    - 24899 29583     7     -  136 14.1       00:07 openspades
    R     -     -     - 29583 62.5    -       00:07 -
    S     -     -     - 29584  0.0    -       00:07 -
    S     -     -     - 29590  2.0    -       00:05 -
    R     -     -     - 29593 42.3    -       00:03 -
    S     -     -     - 29594 44.6    -       00:03 -
    S     -     -     - 29595 42.0    -       00:03 -
    R     -     -     - 29596 38.0    -       00:03 -

After closing it:

    S  PPID   PID THCNT   TID %CPU %MEM     ELAPSED COMMAND
    - 24899 29583     6     -  181 14.1       01:33 openspades
    S     -     -     - 29583 54.6    -       01:33 -
    S     -     -     - 29590  2.5    -       01:31 -
    S     -     -     - 29593 32.6    -       01:29 -
    S     -     -     - 29594 32.9    -       01:29 -
    S     -     -     - 29595 32.3    -       01:29 -
    S     -     -     - 29596 32.4    -       01:29 -

After starting it a second time:

    S  PPID   PID THCNT   TID %CPU %MEM     ELAPSED COMMAND
    - 24899 29583     6     - 88.1 14.1       03:14 openspades
    S     -     -     - 29583 26.1    -       03:14 -
    S     -     -     - 29590  2.1    -       03:12 -
    S     -     -     - 29593 15.2    -       03:10 -
    S     -     -     - 29594 15.4    -       03:10 -
    S     -     -     - 29595 15.1    -       03:10 -
    S     -     -     - 29596 15.1    -       03:10 -
    -   626 29656     7     -  225 14.0       00:23 openspades
    R     -     -     - 29656 69.3    -       00:23 -
    S     -     -     - 29659  0.0    -       00:23 -
    S     -     -     - 29665  2.7    -       00:21 -
    R     -     -     - 29668 47.0    -       00:19 -
    S     -     -     - 29669 46.6    -       00:19 -
    S     -     -     - 29670 45.2    -       00:19 -
    R     -     -     - 29671 46.4    -       00:19 -

After closing the second instance:

    S  PPID   PID THCNT   TID %CPU %MEM     ELAPSED COMMAND
    - 24899 29583     6     - 70.0 14.1       04:06 openspades
    S     -     -     - 29583 20.6    -       04:06 -
    S     -     -     - 29590  2.2    -       04:04 -
    S     -     -     - 29593 11.9    -       04:02 -
    S     -     -     - 29594 12.1    -       04:02 -
    S     -     -     - 29595 11.9    -       04:02 -
    S     -     -     - 29596 11.9    -       04:02 -
    -   626 29656     6     -  206 14.0       01:15 openspades
    S     -     -     - 29656 62.5    -       01:15 -
    S     -     -     - 29665  2.5    -       01:13 -
    S     -     -     - 29668 37.8    -       01:11 -
    S     -     -     - 29669 37.3    -       01:11 -
    S     -     -     - 29670 37.1    -       01:11 -
    S     -     -     - 29671 37.0    -       01:11 -

**Note:** You can see that the Parent Process ID is not the same for the two processes. That's because I started the first one from a terminal and the second one using my Window Manager application launcher.

Process output
---------------

Start the launcher and close it:

    [...]
    2017/03/18 04:05:35 [StartupScreenHelper.cpp:330] ------------------
    2017/03/18 04:05:35 [StartupScreenHelper.cpp:624] SDL Capability Query Window finalized
    2017/03/18 04:05:35 [StartupScreenHelper.cpp:627] OpenGL driver is OpenSpades capable: YES
    2017/03/18 04:05:35 [SDLRunner.cpp:411] SDL Version: 2.0.5 hg-10556:007dfe83abf8
    2017/03/18 04:05:35 [SWRenderer.cpp:65] ---- SWRenderer early initialization started ---
    2017/03/18 04:05:35 [SWRenderer.cpp:72] creating image manager
    2017/03/18 04:05:35 [SWRenderer.cpp:75] creating image renderer
    2017/03/18 04:05:35 [SWRenderer.cpp:80] setting framebuffer.
    2017/03/18 04:05:35 [SWRenderer.cpp:84] initializing depth buffer.
    2017/03/18 04:05:35 [SWRenderer.cpp:88] ---- SWRenderer early initialization done ---
    2017/03/18 04:05:35 [Fonts.cpp:76] Font 'SquareFont (Large)' Loaded
    2017/03/18 04:05:35 [Fonts.cpp:38] Loading built-in fonts
    2017/03/18 04:05:35 [Fonts.cpp:44] Font 'Alte DIN 1451' loaded
    2017/03/18 04:05:35 [Settings.cpp:313] WARNING: setting 'cl_showStartupWindow' has multiple descriptors
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    2017/03/18 04:05:35 [SDLRunner.cpp:192] Starting Client Loop
    2017/03/18 04:05:40 [SDLRunner.cpp:220] Close requested by Client
    2017/03/18 04:05:40 [SDLRunner.cpp:301] Leaving Client Loop
    2017/03/18 04:05:41 [Settings.cpp:277] Saving preference to SPConfig.cfg
    2017/03/18 04:05:41 [Settings.cpp:183] Saving preferences to SPConfig.cfg
    [Process ends]

Start the game, and close it:

    [...]
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    2017/03/18 03:48:47 [ConcurrentDispatch.cpp:294] Creating 4 dispatch thread(s)
    WARNING: uniform 'eyeOrigin' not found
    WARNING: uniform 'eyeFront' not found
    WARNING: uniform 'fogDistance' not found
    WARNING: uniform 'viewSpaceLight' not found
    WARNING: uniform 'detailTexture' not found
    WARNING: uniform 'viewMatrix' not found
    WARNING: uniform 'viewMatrix' not found
    WARNING: uniform 'fogDistance' not found
    WARNING: uniform 'rightVector' not found
    WARNING: uniform 'upVector' not found
    WARNING: uniform 'viewMatrix' not found
    WARNING: uniform 'fogDistance' not found
    2017/03/18 03:48:47 [GLFramebufferManager.cpp:608] New GLColorBuffer requested (w = 1920, h = 1080, ifmt = 0x0062)
    2017/03/18 03:48:47 [GLFramebufferManager.cpp:617] Texture allocated.
    2017/03/18 03:48:47 [GLFramebufferManager.cpp:631] Framebuffer created.
    2017/03/18 03:50:07 [SDLRunner.cpp:220] Close requested by Client
    2017/03/18 03:50:07 [SDLRunner.cpp:301] Leaving Client Loop
    2017/03/18 03:50:07 [Settings.cpp:277] Saving preference to SPConfig.cfg
    2017/03/18 03:50:07 [Settings.cpp:183] Saving preferences to SPConfig.cfg
    [Process still controlling the terminal]

Process ending
---------------

Ending the process using a simple _SIGTERM_ signal works. No need to kill it using a _SIGKILL_ signal.
Sending a _SIGTERM_ signal on one of its threads ends the main process too. So, it does not seems to be deadlocked.

System information
--------------------

Operating system: **Linux 4.9.11-1-ARCH x86_64 GNU/Linux** _(ArchLinux)_
OpenSpades: **0.1.1**

Openspades package [from AUR](https://aur.archlinux.org/packages/openspades/):

    Name            : openspades
    Version         : 0.1.1c-1
    Description     : A clone of Voxlap Ace of Spades 0.75
    Architecture    : x86_64
    URL             : http://openspades.yvt.jp/
    Licenses        : GPL3
    Groups          : None
    Provides        : None
    Depends On      : curl  desktop-file-utils  glew  hicolor-icon-theme  mesa  openal  opusfile  sdl2  sdl2_image  xdg-utils
    Optional Deps   : None
    Required By     : None
    Optional For    : terravox-git
    Conflicts With  : None
    Replaces        : None
    Installed Size  : 14.66 MiB
    Packager        : Unknown Packager
    Build Date      : Tue 07 Mar 2017 07:41:27 AM CET
    Install Date    : Tue 07 Mar 2017 07:57:37 AM CET
    Install Reason  : Explicitly installed
    Install Script  : Yes
    Validated By    : None

### PR DESCRIPTION
**Pull request by yvt**
Fixes #604.

### CODE REVIEW

**Comment by yvt** [comment]
@damienflament Can you see if this fixes the issue?

**Comment by theunknownxy** [comment]
It crashes on exit now, but it seems unrelated to the fix: http://pastebin.com/LeGGQn9v

**Comment by damienflament** [comment]
After building from the _patch-safe-queue-deletion_ branch, the process crashes on exit (segmentation fault). No need to kill it.

Backtrace
----------

    2017/03/23 00:32:52 [GLFramebufferManager.cpp:617] Texture allocated.
    2017/03/23 00:32:52 [GLFramebufferManager.cpp:631] Framebuffer created.
    [Thread 0x7fffef607700 (LWP 27494) exited]
    2017/03/23 00:32:55 [SDLRunner.cpp:220] Close requested by Client
    2017/03/23 00:32:55 [SDLRunner.cpp:301] Leaving Client Loop
    2017/03/23 00:32:55 [Settings.cpp:277] Saving preference to SPConfig.cfg
    2017/03/23 00:32:55 [Settings.cpp:183] Saving preferences to SPConfig.cfg

>

    Thread 11 "openspades" received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffd86f9700 (LWP 27499)]
    0x0000000000579f17 in spades::ThreadLocalStorageImplInternal::ThreadExiting (this=0xdc3d00)
        at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:44
    44				void *p = Get();

> (gdb) thread apply all bt

    Thread 11 (Thread 0x7fffd86f9700 (LWP 27499)):
    #0  0x0000000000579f17 in spades::ThreadLocalStorageImplInternal::ThreadExiting (this=0xdc3d00)
        at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:44
    #1  spades::ThreadExiting () at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:52
    #2  0x0000000000579caf in spades::Thread::InternalRunner (th=0x568de90)
        at /home/damien/GitHub/openspades/Sources/Core/Thread.cpp:133
    #3  0x00007ffff7b3a43c in ?? () from /usr/lib/libSDL2-2.0.so.0
    #4  0x00007ffff7b8b8e9 in ?? () from /usr/lib/libSDL2-2.0.so.0
    #5  0x00007ffff78a62e7 in start_thread () from /usr/lib/libpthread.so.0
    #6  0x00007ffff53f754f in clone () from /usr/lib/libc.so.6

>

    Thread 10 (Thread 0x7fffd8efa700 (LWP 27498)):
    #0  0x0000000000579f17 in spades::ThreadLocalStorageImplInternal::ThreadExiting (this=0xdc3d00)
        at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:44
    #1  spades::ThreadExiting () at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:52
    #2  0x0000000000579caf in spades::Thread::InternalRunner (th=0x568d930)
        at /home/damien/GitHub/openspades/Sources/Core/Thread.cpp:133
    #3  0x00007ffff7b3a43c in ?? () from /usr/lib/libSDL2-2.0.so.0
    #4  0x00007ffff7b8b8e9 in ?? () from /usr/lib/libSDL2-2.0.so.0
    #5  0x00007ffff78a62e7 in start_thread () from /usr/lib/libpthread.so.0
    #6  0x00007ffff53f754f in clone () from /usr/lib/libc.so.6

>

    Thread 9 (Thread 0x7fffd96fb700 (LWP 27497)):
    #0  0x0000000000579f17 in spades::ThreadLocalStorageImplInternal::ThreadExiting (this=0xdc3d00)
        at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:44
    #1  spades::ThreadExiting () at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:52
    #2  0x0000000000579caf in spades::Thread::InternalRunner (th=0x55e97d0)
        at /home/damien/GitHub/openspades/Sources/Core/Thread.cpp:133
    #3  0x00007ffff7b3a43c in ?? () from /usr/lib/libSDL2-2.0.so.0
    #4  0x00007ffff7b8b8e9 in ?? () from /usr/lib/libSDL2-2.0.so.0
    #5  0x00007ffff78a62e7 in start_thread () from /usr/lib/libpthread.so.0
    #6  0x00007ffff53f754f in clone () from /usr/lib/libc.so.6

>

    Thread 8 (Thread 0x7fffda43b700 (LWP 27496)):
    #0  0x0000000000579f17 in spades::ThreadLocalStorageImplInternal::ThreadExiting (this=0xdc3d00)
        at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:44
    #1  spades::ThreadExiting () at /home/damien/GitHub/openspades/Sources/Core/ThreadLocalStorage.cpp:52
    #2  0x0000000000579caf in spades::Thread::InternalRunner (th=0x5689eb0)
        at /home/damien/GitHub/openspades/Sources/Core/Thread.cpp:133
    #3  0x00007ffff7b3a43c in ?? () from /usr/lib/libSDL2-2.0.so.0
    #4  0x00007ffff7b8b8e9 in ?? () from /usr/lib/libSDL2-2.0.so.0
    #5  0x00007ffff78a62e7 in start_thread () from /usr/lib/libpthread.so.0
    #6  0x00007ffff53f754f in clone () from /usr/lib/libc.so.6

>

    Thread 5 (Thread 0x7fffe9f4d700 (LWP 27493)):
    #0  0x00007ffff53ed67d in poll () from /usr/lib/libc.so.6
    #1  0x00007fffe449165e in ?? () from /usr/lib/libasound.so.2
    #2  0x00007fffe449192b in snd_pcm_wait () from /usr/lib/libasound.so.2
    #3  0x00007fffe9fa6b41 in ?? () from /usr/lib/libopenal.so.1
    #4  0x00007fffe9fb16c7 in ?? () from /usr/lib/libopenal.so.1
    #5  0x00007ffff78a62e7 in start_thread () from /usr/lib/libpthread.so.0
    #6  0x00007ffff53f754f in clone () from /usr/lib/libc.so.6

>

    Thread 1 (Thread 0x7ffff7faa600 (LWP 27481)):
    #0  0x00007ffff78a757d in pthread_join () from /usr/lib/libpthread.so.0
    #1  0x00007ffff7b3a626 in ?? () from /usr/lib/libSDL2-2.0.so.0
    #2  0x0000000000579b2b in spades::Thread::~Thread (this=0x5689eb0, __in_chrg=<optimized out>)
        at /home/damien/GitHub/openspades/Sources/Core/Thread.cpp:78
    #3  0x0000000000555780 in spades::DispatchThread::~DispatchThread (this=0x5689eb0, __in_chrg=<optimized out>)
        at /home/damien/GitHub/openspades/Sources/Core/ConcurrentDispatch.cpp:245
    #4  spades::DispatchThread::~DispatchThread (this=0x5689eb0, __in_chrg=<optimized out>)
        at /home/damien/GitHub/openspades/Sources/Core/ConcurrentDispatch.cpp:245
    #5  0x00000000005543cf in std::default_delete<spades::DispatchThread>::operator() (this=<optimized out>, 
        __ptr=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:76
    #6  std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> >::~unique_ptr (
        this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:239
    #7  std::_Destroy<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> > > (
        __pointer=<optimized out>) at /usr/include/c++/6.3.1/bits/stl_construct.h:93
    #8  std::_Destroy_aux<false>::__destroy<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> >*> (__last=<optimized out>, __first=0x45d9d20) at /usr/include/c++/6.3.1/bits/stl_construct.h:103
    #9  std::_Destroy<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> >*> (
        __last=<optimized out>, __first=<optimized out>) at /usr/include/c++/6.3.1/bits/stl_construct.h:126
    #10 std::_Destroy<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> >*, std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> > > (__last=0x45d9d40, __first=0x45d9d20)
        at /usr/include/c++/6.3.1/bits/stl_construct.h:151
    #11 std::vector<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> >, std::allocator<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> > > >::_M_erase_at_end (
        this=0x5316058, __pos=0x45d9d20) at /usr/include/c++/6.3.1/bits/stl_vector.h:1436
    #12 std::vector<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> >, std::allocator<std::unique_ptr<spades::DispatchThread, std::default_delete<spades::DispatchThread> > > >::clear (this=0x5316058)
        at /usr/include/c++/6.3.1/bits/stl_vector.h:1210
    #13 spades::(anonymous namespace)::GlobalDispatchThreadPool::~GlobalDispatchThreadPool (this=0x5316030, 
        __in_chrg=<optimized out>) at /home/damien/GitHub/openspades/Sources/Core/ConcurrentDispatch.cpp:287
    #14 0x0000000000554491 in std::default_delete<spades::(anonymous namespace)::GlobalDispatchThreadPool>::operator()
        (this=<optimized out>, __ptr=0x5316030) at /usr/include/c++/6.3.1/bits/unique_ptr.h:76
    #15 std::unique_ptr<spades::(anonymous namespace)::GlobalDispatchThreadPool, std::default_delete<spades::(anonymous namespace)::GlobalDispatchThreadPool> >::~unique_ptr (this=<optimized out>, __in_chrg=<optimized out>)
        at /usr/include/c++/6.3.1/bits/unique_ptr.h:239
    #16 0x00007ffff53416c0 in __run_exit_handlers () from /usr/lib/libc.so.6
    #17 0x00007ffff534171a in exit () from /usr/lib/libc.so.6
    #18 0x00007ffff532b518 in __libc_start_main () from /usr/lib/libc.so.6
    #19 0x00000000004b5aea in _start ()

**Comment by yvt** [comment]
Okay, how about now?

**Comment by damienflament** [comment]
[...]
    2017/03/23 15:40:42 [GLFramebufferManager.cpp:608] New GLColorBuffer requested (w = 1920, h = 1080, ifmt = 0x0062)
    2017/03/23 15:40:42 [GLFramebufferManager.cpp:617] Texture allocated.
    2017/03/23 15:40:42 [GLFramebufferManager.cpp:631] Framebuffer created.
    [Thread 0x7fffe999f700 (LWP 1012) exited]
    2017/03/23 15:40:44 [SDLRunner.cpp:220] Close requested by Client
    2017/03/23 15:40:44 [SDLRunner.cpp:301] Leaving Client Loop
    2017/03/23 15:40:44 [Settings.cpp:277] Saving preference to SPConfig.cfg
    [Thread 0x7fffef607700 (LWP 1005) exited]
    2017/03/23 15:40:44 [Settings.cpp:183] Saving preferences to SPConfig.cfg
    [Thread 0x7fffd55fd700 (LWP 1016) exited]
    [Thread 0x7fffd5dfe700 (LWP 1015) exited]
    [Thread 0x7fffe0f0a700 (LWP 1014) exited]
    [Thread 0x7fffd4dfc700 (LWP 1017) exited]
    AL lib: (EE) alc_cleanup: 1 device not closed
    [Thread 0x7ffff7faa600 (LWP 1001) exited]
    [Inferior 1 (process 1001) exited normally]

Works fine !

**N.B:** I always seen the message about the audio device not closed:
> AL lib: (EE) alc_cleanup: 1 device not closed

Not a problem.

**Pull request merged**
