### PR TITLE
packaging: add Gnu Guix pkg for OpenSpades

### PR DESCRIPTION
**Pull request by o-nly**
to build with guix:
`guix package -f guix/guix.scm'

[Gnu Guix](https://guix.gnu.org/) is a Free/Libre package manager. I was playing OpenSpades yesterday on a different OS. I thought I'd try to package it for Guix today.

give it a spin and report problems.

### CODE REVIEW

**Comment by godwhoa** [comment]
Another way to install openspades is cool and all, but are you willing to maintain this in the future?

**Comment by o-nly** [comment]
yeah, i do.

**Comment by NotAFile** [comment]
I don't think it's a great idea to maintain packaing for every distribution and in-tree, especially with the unmaintained ones present there already.

I think maintaining this packaging info in a separate repo like upstream Guix does would be much preferrable.

**Comment by o-nly** [comment]
> I think maintaining this packaging info in a separate repo like upstream Guix does would be much preferrable.

Upstream is strict about FOSS licensing. Non-strict [Nonguix](https://gitlab.com/nonguix/nonguix) will be a suitable home for this package.

**Comment by NotAFile** [comment]
There had been work on freely licensed assets, but I think that died down due to a lack of interest.

**Pull request closed without merging**
