### PR TITLE
#373 Fill weapon clip when ammo is restocked.

### PR DESCRIPTION
**Pull request by someoneigna**

### CODE REVIEW

**Comment by Kurtoid** [comment]
:+1:

**Comment by yvt** [comment]
Thank you!

**Comment by someoneigna** [comment]
You are welcome!

**Comment by Rootmars** [comment]
Is this vanilla behavior? This does not seem to be the case for .75

**Comment by feikname** [comment]
Judging from latest `Sources/Client/Weapon.cpp`, I assume this was not the correct behaviour and was fixed later. Please anyone let me know if I am wrong.

**Pull request merged**
