### PR TITLE
Sync test

### PR DESCRIPTION
**Pull request by feikname**

### CODE REVIEW

**Comment by feikname** [comment]
@yvt I fucked up

**Comment by VelocityRa** [comment]
If you're gonna do it do it fast, before anyone pulls.

**Comment by feikname** [comment]
@VelocityRa I will wait for yvt's approval first

**Comment by VelocityRa** [comment]
I can sympathize with that... github could make the target and source repo more clear but they chose to say "base" and "head" repo/branch for whatever reason.

**Comment by VelocityRa** [comment]
Probably wise to see what you're merging anyway before pressing the button though :P

**Comment by feikname** [comment]
@VelocityRa Definitely doing that from now on :laughing:

**Comment by feikname** [comment]
**EDIT**: Submitted a forced push for fixing things

**Comment by yvt** [comment]
No problem

**Pull request merged**
