### PR TITLE
WIP: Screen Space Ambient Occlusion

### PR DESCRIPTION
**Pull request by yvt**
shot0244

### CODE REVIEW

**Comment by damienflament** [comment]
I see that there is some more translatable text introduced by this feature in the GUI.
How will we be advised to update the translation files ?

**Comment by feikname** [comment]
@damienflament usually someone will run `update-pot.sh` before merging the pull request, which updates the `openspades.pot file`. After `openspades.pot` is updated, the process to update your translation is the following: (via *Poedit*)

1 If you haven't already, clone your fork
2. [Sync your fork](https://help.github.com/articles/syncing-a-fork/) (you can also recreate the fork if syncing is causing to much trouble)
3. Open your `Resources/Locales/*LANGUAGE*/openspades.po` file in Poedit
4. Select "Catalog" -> "Update from POT File" in the menu (upper part of program)
5. Translate the new strings
6. Submit the changes to your fork (`git add *`, `git commit -m "Update fr translation"`)
7. Submit a pull request using GitHub

**Comment by feikname** [comment]
@yvt I fucked up a bit by accidentally merging #516 into here. Please fix it before merging this pull request.

**Comment by feikname** [comment]
@damienflament it's possible to update your translations already ;)

**Comment by damienflament** [comment]
I'm on it !

**Comment by roboman2444** [comment]
You can do neat things like deferred screen space directional occlusion if you give it some gbuffers.

So either the "depth-only prepass" needs to also render normals + other info to gbuffers in the same pass, or you can switch up the order of things.


If you do render that information in the prepass, then you can go full deferred lighting and do the sun + ambient in a single fullscreen quad, and the dlights in bounding volumes or more advanced techniques like tiled deferred. Should save a bunch of draw calls, but the amount of memory bandwidth required might go up.

It really depends on weather the game is draw call bound or not.

**Pull request merged**
