### PR TITLE
FreeType2 font renderer

### PR DESCRIPTION
**Pull request by yvt**
Ported from the `ngspades` branch with some additions.

Demonstrating custom TTF/OTF support:

(The font used here is [Google Noto Sans CJK JP](https://www.google.com/get/noto/help/cjk/).)

All texts, especially CJK ones are rendered at much better quality. Installing custom fonts will be much easier, as users no longer have to convert a font before using it.

- [x] Travis CI build fails for some reason

### CODE REVIEW

**Comment by kmsiapps** [comment]
Wow, It looks perfect! ;)

**Comment by feikname** [comment]
````Text
In file included from /home/travis/build/yvt/openspades/Sources/Client/FTFont.cpp:22:0:
/usr/include/ft2build.h:56:38: fatal error: freetype/config/ftheader.h: No such file or directory
 #include <freetype/config/ftheader.h>
````

Missing dependency?

**Comment by feikname** [comment]
I will test somthing I found [here](https://github.com/matplotlib/matplotlib/issues/3029/)

**Comment by feikname** [comment]
Nice 👍

**Pull request merged**
