### PR TITLE
sync dd's wallhack for spectator

### PR DESCRIPTION
**Pull request by SnipersDoubt**

### CODE REVIEW

**Comment by SnipersDoubt** [comment]
Sorry, don't know how GitHub works. I didn't mean to interact with master

**Comment by NotAFile** [comment]
I suppose it's too late now, but I'd like to say that I am not a fan of spectator wallhack code being publicly released. The skill required to comment out the spectator team check in the source and recompile is much lower than the skill required to patch a binary.

**Comment by SnipersDoubt** [comment]
I was just crudely copying and pasting the already public source from DD (#807) just the spectator team check section, not the actual wall hack. Within the safety of my fork, I created a pull request thinking that I could sync that branch to my own master. I was really embarrassed to realise this was not the case.
Sorry for the inconvenience @NotAFile

**Comment by SnipersDoubt** [comment]
I am facepalming so hard now. References can be seen on the other issue.
I just didn't want to put the link in and look like I'm purposely trying to be annoying by making it public.

**Pull request closed without merging**
