### PR TITLE
Provide an option to browse the config directory

### LINKED ISSUE #268: "Reveal user resource directory"
[The user resource directory](https://github.com/yvt/openspades/wiki/Directories) is usually in a hidden directory, which makes it difficult to find by some users.

### PR DESCRIPTION
**Pull request by yvt**
Fixes #268.

- [x] Check if it works on macOS
- [x] Check if it works on Linux
- [x] Check if it works on Windows

### CODE REVIEW

**Comment by feikname** [comment]
I can check on Windows right now,

**Comment by yvt** [comment]
@feikname Is it working? (It can be found in the startup configuration window → Generic tab)

**Comment by feikname** [comment]
@yvt the build is failing in VS 2015. I will get more info and edit this comment soon.

**Comment by yvt** [comment]
@feikname Moved `#include <sys/wait.h>` to inside of `#else` block of `#ifdef WIN32`.

**Comment by feikname** [comment]
Will test changes now.

**Comment by feikname** [comment]
@yvt still failing.

````text
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'return': cannot convert from 'std::string' to 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>'	OpenSpades	C:\Users\NewFlavio\Downloads\openspades-patch-open-userdir (1)\openspades-patch-open-userdir\Sources\Core\ShellApi.cpp	41	
Error	C2664	'std::wstring `anonymous-namespace'::WStringFromUtf8(const char *)': cannot convert argument 1 from 'const std::string' to 'const char *'	OpenSpades	C:\Users\NewFlavio\Downloads\openspades-patch-open-userdir (1)\openspades-patch-open-userdir\Sources\Core\ShellApi.cpp	53	
Error	C2440	'static_cast': cannot convert from 'HINSTANCE' to 'int'	OpenSpades	C:\Users\NewFlavio\Downloads\openspades-patch-open-userdir (1)\openspades-patch-open-userdir\Sources\Core\ShellApi.cpp	59	
````

**Comment by feikname** [comment]
@yvt It's working now, but it doesn't open the correct folder in my Windows 10.

It's opening "My documents" folder.

**Comment by feikname** [comment]
@yvt It's working now! It opens directly into my `%APPDATA%\OpenSpades\Resources` folder.

**Comment by feikname** [comment]
@yvt It's also working on my Ubuntu GNU/Linux.

I guess this is ready to merge.

**Comment by yvt** [comment]
@feikname Thank you for testing it!

**Comment by feikname** [comment]
No problem.

Now OpenSpades [0.1.0](https://github.com/yvt/openspades/milestone/1) is very close to be ready! :)

**Comment by noway421** [comment]
off topic, how did you make such table in the thread? is it a copy-paste or manual formating?

**Comment by feikname** [comment]
@noway421 I opened the error list of VS 2015 and then:
 1. CTRL-A (select all) 
 2. Right Click
 3. Select all

And pasted here in the default ugly format. Sometime later I manually formatted to table format to improve readability. I could've also used [this very nice online tool](http://www.tablesgenerator.com/markdown_tables), but I forgot it existed.

**Pull request merged**
