### PR TITLE
Update dutch translations

### PR DESCRIPTION
**Pull request by Tapmemer**
dutch translations for openspades.

### CODE REVIEW

**Comment by Tapmemer** [comment]
Oke

**Comment by yvt** [comment]
Hi @Tapmemer,

Some strings were added since this PR and I'm planning to release a new version this month. If you want to translate them, please e-mail me so I can send you an invitation link to Crowdin (translation platform).

**Comment by Tapmemer** [comment]
alrigt is fine...

@feikname due to school and irl stuff i havent been able to also give the nl.json file but ill be on it now

**Comment by feikname** [comment]
@Tapmemer Actually, I created the `nl.json` file and @yvt merged it 45 days ago, so no worries :)

**Comment by Tapmemer** [comment]
so dutch is now in the release? nice.

**Pull request merged**
